name: C

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'include/**'
      - 'makefile'

jobs:
  clang-format:
    name: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'src'
            exclude: '(glad)'
          - check: 'include'
            exclude: '(cglm|cimgui|glad|GLFW|KHR|stb)'
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
  build:
    name: build
    runs-on: ubuntu-latest
    needs: clang-format
    steps:
      - uses: actions/checkout@v4
      - run: make clean && make -j$(nproc)

